### ISSUE TITLE
Do you have 2d/3d human poses annotations in this dataset?

### ISSUE THREAD

**Issue by wangzheallen** [VideoObjectSearch/RandPerson#1]

**Comment by Yanan-Wang-cs** [comment]
We do have this data, and will release it later.

**Comment by ShengcaiLiao** [comment]
The 2D keypoint annotations on the cropped person images have been released now.

**Comment by Yanan-Wang-cs** [comment]
In this experiment, we recorded the transition position of the key point in the camera (including x, y z). Unity can get the 3D position of the character in the environment.
