### ISSUE TITLE
Do you have person or body parts segmentation annotations in this dataset?

### ISSUE THREAD

**Issue by renderless** [VideoObjectSearch/RandPerson#2]

**Comment by ShengcaiLiao** [comment]
No, only keypoints. From keypoints segmentation could be roughly estimated, though.

For body segmentation you can have a look of the PersonX project, where it is possible to adapt their MATLAB script to segment the whole body. However, body parts are also not able to be segmented there, and their method cannot handle multiple persons moving together.
