### ISSUE TITLE
Download Links fail from Baidu

### ISSUE THREAD

**Issue by KeYunLee** [VideoObjectSearch/RandPerson#5]
Hi, 
Thanks for the dataset.
I am downloading the dataset, and the subset can be downloaded from Google. but the all data cannot be downloaded from Baidu.
Can you check it?
Thanks.

**Comment by Yanan-Wang-cs** [comment]
Hi,
Thanks for your attention.
Could you describe your operation on Baidu？
By the way, do you use the code "v6mt" to access the data?
Thanks.

**Comment by KeYunLee** [comment]
Hi, 
Thanks for your feedback.
I find out root course due to IP issue...
Current can be downloaded from Baidu.
Thank you very much.
