### ISSUE TITLE
Can you release the grnerated 3D human models?

### ISSUE THREAD

**Issue by LinlyAC** [VideoObjectSearch/RandPerson#7]
Thank you for the good work.

Can you release the grnerated 3D human models? 
If it is inconvenient, can you release the code for generating the 3D model in MakeHuman Software?

Thank you very much.

**Comment by Yanan-Wang-cs** [comment]
Thanks for your attention.

We have released the code for generating the 3D model in [https://github.com/VideoObjectSearch/RandPerson/tree/master/generateCode/generate_human_by_img](https://github.com/VideoObjectSearch/RandPerson/tree/master/generateCode/generate_human_by_img)

You can put the generated model into MakeHuman to export the character.

**Comment by LinlyAC** [comment]
Thank you very much.
